### ISSUE TITLE
T0 - Formato Outputs

### ISSUE THREAD

**Issue by tvonplessing** [IIC2133-PUC/2023-1#10]
Tengo una duda con los outputs, en el CONTEO-PARCIAL utilizamos "Candidat**e**" pero en los otros outputs, como por ejemplo CONTEO-TOTAL utilizamos "Candidad**o**" . Seguimos lo que sale en el enunciado o utilizamos "Candidat**o**" para todo????

**Comment by Dafnemami** [comment]
Hola! Ocupa candidato. Aún no se liberan los test cases, pero de ser el caso solo tendrías que pasar de candidato a candidate para que tu output coincida con el output esperado (el output esperado te lo pasamos, así que vas a saber que poner en tu tarea de inmediado al verlo :) )

🏎️
