### ISSUE TITLE
Liberar memoria de arreglos de arreglos

### ISSUE THREAD

**Issue by morbeta1234** [IIC2133-PUC/2023-1#11]
Hola! 
Quería preguntar como sería la forma correcta en la cual realizar free de un arreglo de arreglos. ¿Debería realizar el free para el arreglo grande o tengo que ir por cada arreglo del arreglo liberando la memoria? Por ejemplo, ¿Cómo sería la correcta liberación del arreglo de arreglos realizado en la diapo 76 del pdf 07-Memoria?

También quisiera saber cómo puedo liberar un arreglo dentro de este arreglo de arreglos, donde quisiera liberar la info(arreglo) de esa "posición" del arreglo para insertar un nuevo arreglo.
Muchas gracias de antemano!

**Comment by Dafnemami** [comment]
Debes ir liberando la memoria de los arreglos dentro del arreglo. Una vez terminas ese, liberas la memoria pedida para el arreglo. Si pienso al arreglo de arreglo como una matriz, liberar la memoria es algo así como lo siguiente:

```c
for(int i = 0; i < N; i++) {
    free(fila[i]);
}
free(matrix);
``` 

Al liberar memoria siempre tienes que ir de menos a mas.

Así mismo, la idea se repite para el caso en que se haya pedido memoria para los elementos que dicha matriz almacena. Esto es, primero debes recorrer la matriz y liberar memoria de los elementos de dicha matriz, para luego realizar lo que te comenté al principio.
