### ISSUE TITLE
DUDAS PARTE C

### ISSUE THREAD

**Issue by matildeotte** [IIC2133-PUC/2023-1#12]
Hola!

Tengo las siguientes dudas:

1. Al eliminar el candidato sólo tenemos que eliminarle sus votos y traspasárselos a otro? Es decir, cuando imprima el conteo parcial debo nombrar al candidato e indicar que no tiene votos registrados? O ya no debe aparecer en el conteo parcial?
2. Si un candidato es eliminado, ya no debe ser considerado en traspasar-exceso-de-votos? o igual puede recibir votos con este comando?
3. Respecto al output, debe haber un salto de línea entre lo que se imprime por distintas instrucciones o tiene que estar todo junto?

Gracias!

**Comment by Pakarati** [comment]
Hola!

1. Es tal como dices, esto para simplificar la modelación. Entonces se traspasan los votos y el candidato eliminado debe seguir apareciendo en los próximos conteos sin votos.
2. Tal como dices, no se debe considerar como candidato elegible para traspaso de votos una vez eliminado.
3. No debe haber saltos de línea entre instrucciones. Puedes notar que en el ejemplo de input no hay saltos de línea, pues el output se debe ver de manera similar con lo solicitado.

Espero haberte ayudado, éxito con la tarea!
