### ISSUE TITLE
T0 - Empate en distancia ideológica.

### ISSUE THREAD

**Issue by tvonplessing** [IIC2133-PUC/2023-1#13]
Al traspasar los votos siempre va a haber un empate en distancia ideológica entre los 2 candidatos contiguos. A cual de los dos se le traspasa los votos?

**Comment by Pakarati** [comment]
Hola!

Dado un empate en la distancia entre 2 candidatos, se le traspasan los votos al candidato con **menor id**. En este ejemplo espero que quedo más claro:

<img width="433" alt="image" src="https://user-images.githubusercontent.com/80866575/225787303-02b289ae-d1d8-4f4f-bbf4-e05b4280f890.png">

Mucho éxito!
