### ISSUE TITLE
T0 - Parte A, formato de impresión

### ISSUE THREAD

**Issue by jlizamajara** [IIC2133-PUC/2023-1#15]
Hola!
Tengo una duda con respecto al formato de impresión en el evento `CONTEO-PARCIAL`, al referirse al candidato aparece CANDIDATE en vez de CANDIDATO, como en el resto de los eventos. Pregunto cuál de los dos debemos considerar, debido a la corrección automática.
Muchas gracias! ૮ ˶ᵔ ᵕ ᵔ˶ ა

**Comment by CarloGauss33** [comment]
Holaa. Sii, se nos paso eso. En los tests esta exactamente igual que en el enunciado. para asi evitar problemas con quienes ya hicieron la tarea. Por lo que en conteo parcial entrega como "CANDIDATE" y en los otros como "CANDIDATO" jajaja
