### ISSUE TITLE
T0 - Parte C - TRASPASAR-EXCESO-VOTOS

### ISSUE THREAD

**Issue by gvfigueroa** [IIC2133-PUC/2023-1#16]
Hola! 
Intentando implementar la función TRASPASAR-EXCESO-VOTOS me surgió una duda: El input que entrega es solamente un valor M de votos, con el cual nosotros debemos encontrar al candidato que tenga una cantidad mayor o igual a ese valor? O el ganador es simplemente el candidato con más votos, independientemente de que alcance este valor? Pregunto esto porque en caso contrario puede existir la posibilidad de que se entregue un valor M que sea mayor a la cantidad de votos de todos los candidatos y en ese caso no hay ganador. Ahora la última duda, si hay 2 candidatos con la misma cantidad máxima de votos, quien gana?

Gracias desde ya!

**Comment by CarloGauss33** [comment]
No entendi. El input a entregar en esa operacion incluye 2 valores. el ID del candidato que traspasa y el valor M
<img width="844" alt="image" src="https://user-images.githubusercontent.com/45949389/226063688-9da6a363-6e32-40fa-aef8-7fb539e7e352.png">

**Comment by gvfigueroa** [comment]
Es que en el código base sólo se lee un int M desde el input, por eso me confundí y pensé que nosotros debíamos buscar al cadidato ganador. Pero sólo seguiré lo que dice el enunciado, gracias!

**Comment by a-ck** [comment]
Hola, tengo una duda con respecto a esto también. Nosotros recibimos al candidato ganador independiente si es el que tiene más votos o no?

**Comment by a-ck** [comment]
Otra duda jeje, tendríamos que modificar el código base o no? porque ahora solo sale:
`int M; `<br>`
fscanf(input_file, "%d", &M);`
y debería salir:
`int candidate_ID, M;`<br>`
fscanf(input_file, "%d %d", &candidate_ID, &M);`

**Comment by CarloGauss33** [comment]
sip

**Comment by a-ck** [comment]
ese sip es una respuesta a las 2 preguntas que hice vdd?

**Comment by CarloGauss33** [comment]
Si, jajaj. Ambos son ints, por lo que es valido definirlo asi

**Comment by CarloGauss33** [comment]
Ahora vi la otra pregunta jajaj.

> Hola, tengo una duda con respecto a esto también. Nosotros recibimos al candidato ganador independiente si es el que tiene más votos o no?

Claro, el comando entrega explicitamente el candidato sobre el cual se operara. por lo que da lo mismo si realmente no es el con más votos

**Comment by a-ck** [comment]
agradecida
