### ISSUE TITLE
Parte B: Ordenar candidatos

### ISSUE THREAD

**Issue by rfigueroa314** [IIC2133-PUC/2023-1#17]
Hola, en el enunciado sale "Esta acción se dedica a IMPRIMIR los candidatos por orden de mayor a menor votos recibidos como
**primera opción**."

A que se refiere con primera opción?

**Comment by CarloGauss33** [comment]
Disculpa se nos quedo esa palabra desde una iteracion anterior de enunciado. Actualmente los votos solo tienen una opcion por lo que da lo mismo eso. Lo borraremos
