### ISSUE TITLE
Ordenar candidatos y su efecto en otras operaciones

### ISSUE THREAD

**Issue by mariagonthier** [IIC2133-PUC/2023-1#18]
Hola buenas!!

No me queda claro a qué va en ORDENAR-CANDIDATOS el "OJO: El comportamiento en el resto de las operaciones no se debería ver afectado por esta operación". 

Me imagino que es que todos los prints en las otras operaciones son por orden ascendente de ID de los candidatos y si se ordenaran los candidatos por cantidad de votos estas otras operaciones debiesen seguir imprimiendo según id no? o hay otros factores que considerar?

Siguiendo la misma línea,  quiero saber si en el CONTEO-PARCIAL, dentro de un mismo candidate, los prints de los voters debiesen seguir algún orden en específico (ej: por orden ascendente de voterId).

Muchísimas gracias :)

**Comment by CarloGauss33** [comment]
Hola! 
1. Claro, la idea es que si hay 10 candidatos si se pide la operacion conteo o conteo parcial igualmente se muestren de la forma 0, 1, 2....
Al final la idea es que el sorting no afecte el comportamiento futuro del programa

2. Según el orden de llegada
