### ISSUE TITLE
T0 - Parte A (Cantidad de votantes)

### ISSUE THREAD

**Issue by LissScarlett** [IIC2133-PUC/2023-1#2]
Hola! Para la parte A del procesamiento de votos, dice que tenemos una cantidad fija de N candidatos y V votantes, sin embargo en el input de ejemplo solo está la cantidad de N candidatos (por enunciado entiendo que no sabemos la cantidad de votos para cada candidato, pero en la descripción del problema dice "votos que te entregaremos" haciendo referencia a los votos totales emitidos). Está correcto que no nos entreguen la cantidad total de votantes (o votos emitidos)? Ya que de no entregárnoslo, solo se me ocurre asumir como peor caso (pensando en memoria) que cada candidato reciba en alguna votación, todos los votos y también suponiendo que cada evento fuese un voto y no otro evento. Mi duda va más que nada para poder trabajar bien en memoria y/o saber si omití alguna información entre líneas. 

Muchas gracias!!

**Comment by CarloGauss33** [comment]
Hola @LissScarlett, disculpa esa linea. de "V votantes fijos" esta de más. Ya la elimine del enunciado. Realmente solo N es dado y la cantidad de votantes/votos no se sabe a priori. SI no que llegan a modo de eventos durante el flujo de los eventos

**Comment by vcrb18** [comment]
Me sumaré a esta pregunta. Para obtener el número de votantes, solo se me ocurre iterar por el input sabiendo el número de eventos. Así puedo armar mis estructuras de datos con las que trabajaré en la tarea. Pero el código está hecho de tal manera que programar en las partes que ustedes señalan rompería ese "sistema", y además haría que tuviera que iterar dos veces por todo el input, lo cual claramente no es eficiente. ¿Hay algo que no esté viendo en lo que me puedan ayudar?

**Comment by CarloGauss33** [comment]
@vcrb18 No necesitas saber el numero de votantes. La idea es que utilices alguna estructura que te de la flexibilidad de poder recibir votos "on-demand"
