### ISSUE TITLE
T0 - Anular voto de candidateID inválido

### ISSUE THREAD

**Issue by alonsogm4** [IIC2133-PUC/2023-1#20]
Hola! En la sección de `ANULAR-VOTO` se detalla el comportamiento en caso de que el `voterID` entregado no exista, pero el `candidateID` siempre será válido?

**Comment by fddelabarra** [comment]
Hola!

Si, ```candidateID``` siempre será valido : )

**Comment by sbersanii** [comment]
Hola, en el servidor hay un test de los B que me está saliendo erroneo (Medium B-1 Específicamente), me tinca que puede ser por el formato de la respuesta, ya que en los test que nos entregaron no existen casos de anular un voto que no exista. Es decir, cuando debemos responder : "NO SE ENCONTRO UN VOTO VALIDO CON ID voterID", podrían revisar si está bien ese formato pls o quizás está con otra respuesta.                      Saludos y gracias!!
