### ISSUE TITLE
T0 - Orden al traspasar votos

### ISSUE THREAD

**Issue by tvonplessing** [IIC2133-PUC/2023-1#21]
Tengo una duda de la forma en que se traspasan los votos, si tengo los candidatos 1 y 2 de la siguiente forma:

		CANDIDATE 1
		VOTE 7
		VOTE 29
		VOTE 59
		VOTE 98
		VOTE 151
		VOTE 166
		VOTE 170
	CANDIDATE 2
		VOTE 48
		VOTE 58
		VOTE 63

Y el candidato 2 es eliminado, por lo que se le traspasan todos sus votos al candidate 1, el traspaso de votos debería verse así para el candidate 1:

		CANDIDATE 1	
		VOTE 7	
		VOTE 29	
		VOTE 59	
		VOTE 98	
		VOTE 151	
		VOTE 166	
		VOTE 170	
		**VOTE 63	
		**VOTE 58	
		**VOTE 48

O bien así:

	CANDIDATE 1
		VOTE 7
		VOTE 29
		VOTE 59
		VOTE 98
		VOTE 151
		VOTE 166
		VOTE 170
		**VOTE 48
		**VOTE 58
		**VOTE 63

Es decir se traspasan siempre primero los últimos votos que recibió candidate 2 o bien es al revés?

**Comment by nsantama** [comment]
La segunda manera es la correcta, es decir, se traspasan en el mismo orden que estan en los votos del candidato original.
En el ejemplo seria:
```
CANDIDATE 1
	VOTE 7
	VOTE 29
	VOTE 59
	VOTE 98
	VOTE 151
	VOTE 166
	VOTE 170
CANDIDATE 2
	VOTE 48
	VOTE 58
	VOTE 63
```
Pasa a ser:
```
CANDIDATE 1
	VOTE 7
	VOTE 29
	VOTE 59
	VOTE 98
	VOTE 151
	VOTE 166
	VOTE 170
	**VOTE 48
	**VOTE 58
	**VOTE 63
```
