### ISSUE TITLE
T0 - Tiempo de computo

### ISSUE THREAD

**Issue by tvonplessing** [IIC2133-PUC/2023-1#22]
Tengo una duda con el tiempo de cómputo, al correr mi código funciona bien para los casos easy , pero con los medium se demora más de 10s, no se si es porque mi computador es lento (tiene 5 años) o es que la forma en que realizó las operaciones es ineficiente.

**Comment by fddelabarra** [comment]
Hola!

Podrias probar correr los test del servidor con tu codigo, si el tiempo es más de 10 ahí, quiere decir que es por operaciones ineficientes en tu código y no por tu computador.

Espero te sirva :)
