### ISSUE TITLE
T0 - Timeout

### ISSUE THREAD

**Issue by aboehmg** [IIC2133-PUC/2023-1#24]
¡Hola! He probado mi tarea con los testcases de grade unas ~20 veces. En 2 de estos casos un caso (hard-A1) me ha hecho timeout y en todos los otros el mismo test ha corrido entre 6 y 8 segundos. ¿Debo seguir modificando mi código o me puedo despreocupar?

**Comment by CarloGauss33** [comment]
Sacale captura a cuando este bien en el tiempo. Y despreocupate

**Comment by denisseleiva** [comment]
Hola! Con respecto a esto @CarloGauss33 
Me sucedió lo mismo y ya saqué el pantallazo. Este lo debemos poner en el readme del repo? O lo usamos para pedir recorrección después?

**Comment by CarloGauss33** [comment]
Para pedir recorreccion despues. La idea es que el dia que publique las notas. Me avisan y se las actualizo (En caso de que el corrector de timeout)
