### ISSUE TITLE
T0 - Tests públicos y privados

### ISSUE THREAD

**Issue by Amandasandov** [IIC2133-PUC/2023-1#25]
Hola, he probado en el servidor correr tanto los test como los grade. Tengo el output correcto en todos los test públicos pero wrong output en tres test privados de grade. No se como corregir los errores porque no se me ocurre en que me puedo estar equivocando. ¿Me podrian dar alguna sugerencia? De antemano muchas gracias.

**Comment by CarloGauss33** [comment]
Hola! en que tests ocurre esto? Para asi contrastar bien los grade y ajustarlos en caso de que esten evaluando casos borde

**Comment by CarloGauss33** [comment]
Acabo de actualizar los grade de la parte C. Vuelve a intentar. Elimine un caso borde que no deberia ser considerado

**Comment by Amandasandov** [comment]
Hola, lo volvi a intentar y ahora me salen todos correctos, muchas gracias
