### ISSUE TITLE
T0 - Asumir orden ids & tabs

### ISSUE THREAD

**Issue by mariagonthier** [IIC2133-PUC/2023-1#26]
Hola!

Podemos asumir que los id de los candidatos van del 0 al n-1 ? Es decir, que si N=3, los candidatos van a ser 0,1,2 y no 40,35,7.

Lo otro, ¿A qué numero de espacios son equivalentes los tabs requeridos en los distintos prints?

Gracias :):):)

**Comment by Pakarati** [comment]
Hola!

Efectivamente es como dices, puedes asumir que los id de los candidatos estarán entre 0 y N-1 (lo puedes comprobar con los test y soluciones que fueron recientemente subidos :D )

Por otro lado, un tab equivale a 4 espacios (puedes utilizar `\t` ). Te dejo un ejemplo más visual, lo marcado corresponde a un tab: 

<img width="163" alt="tabs" src="https://user-images.githubusercontent.com/80866575/226448642-c8ef92c1-8470-433b-9284-02d10e9774d6.png">

Mucho éxito!
