### ISSUE TITLE
T0 - Traspasar exceso de voto 

### ISSUE THREAD

**Issue by tvonplessing** [IIC2133-PUC/2023-1#27]
Hola! Tengo tres dudas:

1. EN el caso de que V-M sea igual a 0 se imprime?

{{ NOMBRE CANDIDATO B}} HA RECIBIDO 0 VOTOS

2. en el caso de que un candidato sea eliminado, puede ser elegido? 

3. En el caso contrario, un candidato que se haya elegido puede ser eliminado?

**Comment by CarloGauss33** [comment]
Holaa

1. Correcto, se imprime que se transfirieron 0 votos
3. No, luego de que un candidato sea eliminado, no puede ser elegido.
4. Tampoco

**Comment by camirojasguajardo** [comment]
En qué formato se debe poner que se transfirieron 0 votos? Se debe igual calcular el candidato más cercano?

**Comment by kalarconvl** [comment]
¿Puede pasar que la cantidad de votos del candidato al que se le traspasan los votos + el exceso sea mayor que M? ¿Da lo mismo?

**Comment by CarloGauss33** [comment]
@camirojasguajardo Sip. se debe imprimir que se transfirieron 0 votos, igualmente se debe calcular la cantidad

**Comment by CarloGauss33** [comment]
@kalarconvl Si puede pasar. Da lo mismo, la idea del evento es más que nada que el candidato que se entrega (CandidateID). Pase los votos. Da lo mismo si es él con más votos o no. (Y también daría lo mismo la cantidad del que recibe)
