### ISSUE TITLE
T0 - Paso de votos

### ISSUE THREAD

**Issue by pedrodepabloi** [IIC2133-PUC/2023-1#28]
Hola, viendo el comportamiento del traspaso de votos que se muestra en el enunciado:
![duda t0](https://user-images.githubusercontent.com/80767669/226653627-b28eb953-1b80-4da9-9076-257ed4e135f9.PNG)
Ocurre que para una cantidad N de Candidatos, el último candidato nunca podrá recibir votos, ya que en el caso de que se elimine el candidato 0, por la regla del menor id, los votos se traspasarán al candidato 1. Entonces, el candidato 1 puede recibir votos de 2 candidatos (0 y 2) pero el candidato N nunca recibirá votos. 
¿Está bien que ocurra esto?, ya que me imagino que la idea es que cada candidato pueda recibir votos de otro.

Quedo atento

**Comment by CarloGauss33** [comment]
Incorrecto. 

Suponte el siguiente caso: (Candidatos numerados de 0 a N-1)

Candidato 0 debe traspasar votos. Por la formula, existen dos opciones, el candidato N-1 y el candidato 1. Acá se distinguiría por menor id. Por lo que 1 ganaría.

Sin embargo, si 1 fue eliminado (Ya sea por eliminación o por ganar). No puede recibir votos, lo que significaría que, en ese caso, los votos se irán a N-1

**Comment by antoniamerino** [comment]
Hola! Y que pasaría si los votos N-1 y 1 ya estan eliminados ( ya sea por eliminacion o por ganar), el cadidato 0 a quien le tendría que transferir los votos?

**Comment by antoniamerino** [comment]
Y otra pregunta al respecto, que pasa si el candidatoA definido como ganador, fue eliminado antes?

**Comment by CarloGauss33** [comment]
Hola @antoniamerino 
1. Al candidato de id 2, ya que su distancia seria 2 (al igual que con N-2). Pero ahi desempata con menor ID

**Comment by CarloGauss33** [comment]
2. Eso no deberia ocurrir nunca. Luego de electo un candidato/eliminado. deja de estar en carrera

**Comment by antoniamerino** [comment]
Perfecto! Gracias
Respecto a lo segundo, el ganador viene definido segun el input con el id del candidato. El id de ese candidato nunca sera el de uno eliminado anteriormente?
Porque los candidatos eliminados seguiran teniendo su id y una cantidad de votos = 0

**Comment by pedrodepabloi** [comment]
> Incorrecto.
> 
> Suponte el siguiente caso: (Candidatos numerados de 0 a N-1)
> 
> Candidato 0 debe traspasar votos. Por la formula, existen dos opciones, el candidato N-1 y el candidato 1. Acá se distinguiría por menor id. Por lo que 1 ganaría.
> 
> Sin embargo, si 1 fue eliminado (Ya sea por eliminación o por ganar). No puede recibir votos, lo que significaría que, en ese caso, los votos se irán a N-1

Perfecto! No habia considerado esa situación. Muchas gracias por la aclaración

**Comment by CarloGauss33** [comment]
> Perfecto! Gracias Respecto a lo segundo, el ganador viene definido segun el input con el id del candidato. El id de ese candidato nunca sera el de uno eliminado anteriormente? Porque los candidatos eliminados seguiran teniendo su id y una cantidad de votos = 0

Correcto. La idea es que luego de eliminado un candidato, ó de que sea "electo" (Con la operacion que transfiere votos). Este candidato ya no esta habilitado para recibir votos ó para pasar. Lo que causa que no pueda ser eliminado nuevamente ni electo
