### ISSUE TITLE
EDD-Docker en Mac

### ISSUE THREAD

**Issue by pancghogarcilazo** [IIC2133-PUC/2023-1#29]
Estoy usando edd-docker para mac, pero para usar valgrind resulta un poco lento tener que copiar el repositorio a la carpeta de edd-docker y luego correr el codigo. Queria saber si existe algun problema en guardar directamente el repositorio en la carpeta de edd-docker/volume. ¿provocaría esto un mal funcionamiento al trabajar con git?

**Comment by CarloGauss33** [comment]
No deberia haber ningun problema

**Comment by MTaisa** [comment]
Yo lo tengo así y no tengo problemas

**Comment by saravialu** [comment]
Hola! Cada vez que trato de probarlo me sale repositorio inválido, que puede ser?
<img width="235" alt="Captura de Pantalla 2023-03-27 a la(s) 22 05 10" src="https://user-images.githubusercontent.com/62360686/228100749-20723123-4470-4fe7-9907-2de6efcf5071.png">

**Comment by CarloGauss33** [comment]
Hola @saravialu. tu mendaje deberia ir en la issue del servidor. Igualmente creo que el problema es que el URL deberia ir sin los corchetes {}
