### ISSUE TITLE
T0 - Problema, Candidatos

### ISSUE THREAD

**Issue by BrunoFarfan** [IIC2133-PUC/2023-1#3]
Hola!

No entiendo bien la parte en la que se explica la parte de la ideología de los candidatos. Se supone que hay solo un tema **X** por cada archivo de input, y los candidatos estarán en orden desde más en contra a más a favor (**0 hasta N-1**)?

Y por otro lado, cuando se define la distancia ideológica, los _i_ y _j_ son los índices de cada candidato, es decir, enteros desde **0 a N-1**?

**Comment by drcid98** [comment]
Me uno a la segunda parte de la duda, no logro entender que valor toman los i,j ya que si fueran enteros tampoco tendría sentido especificar el caso en que |i - j| < 0.5

**Comment by CarloGauss33** [comment]
Hola @BrunoFarfan . Correcto, i y j son los indices de los candidatos. Por otro lado @drcid98 Habia un pequeño error ahi. realmente deberia ser |i-j| < N * 0.5 y N - |i-j|  para el otro caso. Al final la idea es que sea como una rueda (la distancia del ultimo con el primero es 1)
