### ISSUE TITLE
T0 - problema uso del servidor

### ISSUE THREAD

**Issue by denisseleiva** [IIC2133-PUC/2023-1#30]
Hola! No puedo correr mi tarea en el servidor :( por ejemplo al hacer Grade obtengo esto 
<img width="665" alt="Captura de Pantalla 2023-03-22 a la(s) 08 52 26" src="https://user-images.githubusercontent.com/69520522/226896905-5ec2ae8b-4ade-46e6-801b-ea26a8299e0e.png">

Si lo intento en safari obtengo
<img width="702" alt="Captura de Pantalla 2023-03-22 a la(s) 08 56 26" src="https://user-images.githubusercontent.com/69520522/226898215-14c6793a-7d86-404e-a74e-a0643c4fb0f2.png">

Y para hacer Result, se debe subir la carpeta Public_tests_t0/tests ? Porque tampoco me funciona, pero tengo en el .gitignore la carpeta de los tests

**Comment by sachondo7** [comment]
No soy ayudante ni nada, pero entiendo que está caído a mi me pasa lo mismo

**Comment by denisseleiva** [comment]
Ahhh parece que era eso. Ahora funciona pero me sale otro error :(
<img width="743" alt="Captura de Pantalla 2023-03-22 a la(s) 14 02 24" src="https://user-images.githubusercontent.com/69520522/226982052-9b4017e0-f917-4605-b8dc-a8828dd9761a.png">

En mi pc me funcionan los tests hasta los B

**Comment by denisseleiva** [comment]
Ya pude 😄
