### ISSUE TITLE
T0 - Duda acerca de la nota 

### ISSUE THREAD

**Issue by MTaisa** [IIC2133-PUC/2023-1#31]
Hola, una consulta, cómo podemos calcular la nota de la tarea?? Al correrlo en el servidor con grade arroja un 1 si el test se realizó correctamente y 0 de lo contrario, con esos puntos podemos calcular de alguna forma la nota??

**Comment by CarloGauss33** [comment]
Sip. Utilizando la ponderacion de la pauta. 
Para calcular tu nota de Test (90%) de la nota. Calcula tu puntaje por item (A, B, C) con (Puntos obtenidos/Puntaje total item). Y lo multiplicas por la ponderacion de ese item.

Finalmente los resultados los multiplicas por 6 (El puntaje final) y luego sumarle el punto base.


El otro 10% se obtiene al no tener errores ni leaks de memoria
