### ISSUE TITLE
T0 - Posible error en test Debug C1

### ISSUE THREAD

**Issue by pureyesz** [IIC2133-PUC/2023-1#32]
Hola, en la solucion del test Debug-C1 aparece esto:

<img width="330" alt="Screenshot 2023-03-22 at 17 22 52" src="https://user-images.githubusercontent.com/53910586/227029514-907f19f7-1c77-4225-ae2c-392f8c6490c9.png">

Se elimina al candidato 2, cuando se debiese eliminar al candidato 1.

**Comment by CarloGauss33** [comment]
Hola! Fijate que justo antes el candidato 1 habia sido electo. Por lo que no puede ser eliminado

**Comment by sshlpe** [comment]
Disculpa no entiendo, entonces si el candidato 1 fue electo (con "TRASPASAR-EXCESO-VOTOS 1 2") no puede ser eliminado con "ELIMINAR-CANDIDATO"? porque después aparece "TRASPASAR-EXCESO-VOTOS 3 4" entonces el candidato 3 también fue electo y tampoco puede ser eliminado? El evento "ELIMINAR-CANDIDATO" solo elimina candidatos no electos? 
Que pasa si no quedan candidatos no electos o que no hayan sido eliminados? Si un candidato fue electo, puede recibir votos de un candidato eliminado? o de los excesos de votos de otro candidato electo?
 Lo siento pero esto no esta explicado en el enunciado.

**Comment by gecoli** [comment]
Buenas, me sumo a la duda de esta persona y lo comentado por sshlpe. 
En ninguna parte del enunciado dice que al ocupar 'Traspasar votos', el candidato en cuestión no puede ser eliminado, lo que dice es que lo definirá como ganador, aunque no es el resultado final en este caso...

**Comment by sachondo7** [comment]
Me sumo a la pregunta! Tengo exactamente el mismo error. En el enunciado no dice que si fue electo luego no puede ser eliminado.

**Comment by gecoli** [comment]
Incluso arreglando el hecho de que no puede ser 'eliminado', el problema luego radica en el traspaso de votos cuando se elimina a otra persona. 

Si es usado el 'traspaso-exceso-votos' con un candidato en particular, entonces este candidato no puede ser eliminado ni recibir votos de los eliminados?

**Comment by Pakarati** [comment]
Hola a todxs!

Para el caso de los candidatos eliminados, estos no pueden recibir votos posteriores ni tampoco pueden ser electos como ganadores en la parte de Traspaso de votos, por lo que no deberían ser considerados para recibir votos de eliminados ni de traspaso, así como no pueden ser eliminados nuevamente.

En el caso de los candidatos electos, una vez elegidos como ganador, estos ya no pueden ser eliminados, ni tampoco pueden recibir votos de ningún tipo (de traspaso ni de candidatos eliminados). Tampoco pueden ser elegidos nuevamente, pues ya ganaron una vez.

Pueden revisar issues anteriores que están relacionadas al trasapaso de votos: #28 , #27 , #21 , #6 

Espero aclare sus dudas, mucho éxito con la tarea! :)

**Comment by Mahund** [comment]
Tuve la misma duda, tal vez debería explicitarse en el enunciado de `TRASPASAR-EXCESO-VOTOS CANDIDATOA M` que no puede ser considerada para eliminacion y que el codigo que nos pasaron no esta tampoco actualizado para recibir el id del candidato ganador.

**Comment by CarloGauss33** [comment]
Agregada la explicitacion. Habia faltado un push. Si, al codigo base le falta ese input. Aunque basta con agregarlo como dice la issue #16
