### ISSUE TITLE
Problemas al probar código

### ISSUE THREAD

**Issue by pancghogarcilazo** [IIC2133-PUC/2023-1#33]
Tengo problemas al correr el codigo tanto como en el servidor como cuando corro run_tests.sh. Al correr run_tests.sh me devuelve el siguiente error: bash: ./run_tests.sh: /usr/bin/bash: bad interpreter: Permission denied . No he logrado arreglarlo. Al correrlo en el servidor me entrega Wrong output. Hasta el momento pense que ese era el caso a pesar que el output file que creo era identico al de la solución. Corri un comparador de texto y no existian diferencias. Ahora recien corri mi codigo en otro computador y efectivamente funciona. Que puedo hacer?

**Comment by CarloGauss33** [comment]
Holaa. Para que te funcione  ./run_tests.sh ejecuta lo siguiente

```
chmod a+x  ./run_tests.sh
sh  ./run_tests.sh
```

Sobre lo del servidor, en local como te funciona `diff -b`? Esa es la forma que utilizamos para comparar los archivos en el servidor.
