### ISSUE TITLE
Límite gigas de Ram

### ISSUE THREAD

**Issue by sachondo7** [IIC2133-PUC/2023-1#34]
Hola, en el enunciado de la tarea dice que es máximo 1 GB de RAM, pero en el servidor dice MEMORY ERROR al tener más de 1.5 gb, cual es el correcto, ademas, hay alguna forma de ver exactamente cuando ram usa mi programa? Ejecuto htop pero no entiendo nada jeje.

**Comment by CarloGauss33** [comment]
1Gb de ram, ese 1.5Gb del servidor esta de más
