### ISSUE TITLE
T0 - Parte B, problema de formato en ordenar a candidatos 

### ISSUE THREAD

**Issue by andrea1vlib** [IIC2133-PUC/2023-1#35]
Hola, tengo una duda dado que mi algoritmo actualmente ordena a los candidatos según orden de mayor cantidad de votos a menos. Sin embargo, no me entrega exactamente lo mismo que los tests, ya que cuando tienen la misma cantidad de votos no necesariamente lo selecciona de la misma forma. Quería saber si afectará a mi nota ya que podría arrojar que están distintos o si tienen algún criterio para diferenciar cuando ambos números son iguales. 

<img width="728" alt="image" src="https://user-images.githubusercontent.com/62084622/227336951-cd640d60-365e-4d50-9cd3-4aa67381fdd2.png">

**Comment by ignaciaurrutia** [comment]
Me sumo a la duda

**Comment by CarloGauss33** [comment]
Hola @andrea1vlib Lamentablemente afectaria tu nota ya que la evaluacion es determinista y se realiza comparando los output esperados. Para este caso del sorting te recomendaria hacer el sort no "in-place" par aque de esa forma no afectes el orden original de los candidatos

**Comment by andrea1vlib** [comment]
okaa, graciaas
