### ISSUE TITLE
Duda TRASPASAR-EXCESO-VOTOS en main.c

### ISSUE THREAD

**Issue by jlizamajara** [IIC2133-PUC/2023-1#37]
Hola! Tengo una duda sobre el código de main, en la parte de TRASPASO-EXCESO-VOTOS, en esta parte solo se define el int M recibido del archivo .txt de input, entonces añadí que se leyera de este archivo también el ID del candidato electo. Mi duda es que no estoy segura si está bien hacerlo o no.

**Comment by Pakarati** [comment]
Hola! Está bien, pues necesitas el id del candidato. Así que está bien que le agregues eso al código base :)

Éxito con la tarea!
