### ISSUE TITLE
Test Case easy-C0  ELIMINADOS

### ISSUE THREAD

**Issue by Ctrbcb** [IIC2133-PUC/2023-1#38]
Tengo una duda, en el test case easy C0, vi que en la linea 3787 se elimina al candidato 11, pero viendo el conteo parcial anterior, el candidato 2 tiene 6 votos mientras que el 11 tiene 7 votos  y no entiendo por qué se elimina el 11  si el 2 tiene menos votos.
Antes se elige el 2 para traspasar  votos ¿si se elige un ganador ya no puede ser eliminado?

**Comment by Pakarati** [comment]
Hola!

Si te fijas, en la línea 3622 el candidato 2 fue elegido como ganador. Esto evita que sea considerado para eliminación, a pesar de ser el que menos votos tiene. Puedes consultar las issues anteriores tales como #32 donde se explica los casos de candidatos electos y eliminados por si te surgen más dudas para la parte C.

Mucho éxito!
