### ISSUE TITLE
T0 - Parte A. Conteo-Parcial - Caso de votos no registrados

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC2133-PUC/2023-1#39]
Hola! En conteo parcial nos dicen que en caso de no haberse registrado ningún voto, se deberá imprimir "NO HAY VOTOS REGISTRADOS" y justo abajo sale que el TOTAL PARCIAL DE VOTOS es igual a 0. Mi pregunta es ¿ Solamente se debe poner NO HAY VOTOS REGISTRADOS cuando en TOTAL hay 0 votos para todos los candidatos, o cuando un candidato en específico no tiene votos?

Técnicamente puede pasar algo así?:

CONTEO-PARCIAL
    CANDIDATE 1
        NO HAY VOTOS REGISTRADOS
    CANDIDATE 2
        VOTE 4
        VOTE 8
...
CONTEO PARCIAL DE VOTOS: 10

**Comment by CarloGauss33** [comment]
Hola! Nope. Deberias imprimir lo mismo para cada candidato. Por ejemplo

CONTEO-PARCIAL
CANDIDATE 1
NO HAY VOTOS REGISTRADOS
CANDIDATE 2
NO HAY VOTOS REGISTRADOS
CANDIDATE 3
NO HAY VOTOS REGISTRADOS
...
CONTEO PARCIAL DE VOTOS: 0

**Comment by CristobalUrzua** [comment]
Osea esto solo aplica para cuando en total hay 0 votos?
