### ISSUE TITLE
T0- Parte A: Duda Conteo Parcial

### ISSUE THREAD

**Issue by agustinbc7** [IIC2133-PUC/2023-1#4]
Hola, tengo una duda con el conteo parcial. ¿Debe mostrarse el ID de cada votante por cada candidato?
Y otra duda, ¿los ID de los candidatos van desde el 0 hasta el N-1 tal como sucede con los votantes?

**Comment by CarloGauss33** [comment]
1. Si, la idea es que imprimas todos los votos que un candidato recibio.
2. Tambien correcto
