### ISSUE TITLE
T0 - Candidatos Ganadores debug C1

### ISSUE THREAD

**Issue by ferperezh** [IIC2133-PUC/2023-1#40]
Hola escribo porque en la issue #32 se dijo que si un candidato era ganador ya no se podia contar para recibir ni eliminarse. Sin embargo en el mismo test el candidato 2 es ganador cuando el candidato 1 es eligido para traspasar 0 votos, pero luego este mismo candidato es eliminado para darle los votos a candidato a 3. Pero eso no puede ser segun lo establecido en esa issue. 
<img width="272" alt="Captura de Pantalla 2023-03-24 a la(s) 12 52 45" src="https://user-images.githubusercontent.com/69528837/227575978-c6173189-722b-4024-b516-a364800ea98c.png">

**Comment by ferperezh** [comment]
Entonces mi pregunta es que si hay un intercambio de 0 votos tanto como el candidato elegido como el ganador no son excluidos de otras transacciones?

**Comment by nsantama** [comment]
El candidato que se considera ganador es el candidato elegido (en este caso el candidato 1), al que se le traspasan los votos no se considera como ganador y sigue participando, es decir, puede ser eliminado o salir elegido como ganador en un comando futuro.

**Comment by ferperezh** [comment]
Si es elegido pero el ganador es el candidato 2 ya que es el que obtiene "nuevos" votos

**Comment by nsantama** [comment]
El candidato elegido deja de ser considerado, el candidato que recibió los votos sigue siendo considerado para los siguientes comandos

**Comment by ferperezh** [comment]
Pero entonces en el test C0 de la carpeta easy en la ultima linea 

segun la solucion deberia aprecer esto: 
<img width="316" alt="Captura de Pantalla 2023-03-25 a la(s) 17 57 29" src="https://user-images.githubusercontent.com/69528837/227741416-414bf02d-e3de-44d8-a54e-56eb1451b571.png">
Pero a mi me da esto:

<img width="269" alt="Captura de Pantalla 2023-03-25 a la(s) 17 56 12" src="https://user-images.githubusercontent.com/69528837/227741472-37015555-c982-4d95-af10-9f43a625aed6.png">

y creo que la mia esta bien porque un candidato que ya recibió votos puede volver a recibir según con lo que dijiste

Entonces la solución no la entiendo.

**Comment by nsantama** [comment]
Ahi el problema es que el candidato mas cercano a 8 que sigue siendo valido es el 6, pero en tu respuesta toma al candidato 0 como el mas cercano, cuando se tiene que la distancia de 8 a 6 es 2 y la distancia de 8 a 0 es 4
