### ISSUE TITLE
T0 - Dudas test case easy c1

### ISSUE THREAD

**Issue by sachondo7** [IIC2133-PUC/2023-1#42]
![Screenshot 2023-03-24 at 20 08 42](https://user-images.githubusercontent.com/80768647/227659426-701af5d3-5b7a-41c5-9e31-cedd1ee7e60b.png)

Holaa tengo una duda, acá cuando se elige al candidato 2 como ganador, porque el candidato 1 recibiría 7 votos siendo que 13 - 7 = 6? 
No deberían traspasarse los últimos 6 votos en vez de los últimos 7?

**Comment by Pakarati** [comment]
Hola! Si no me equivoco, este es el test C0 cierto?

En ese caso, si te fijas en el input, el M es 6 y la cantidad que posee el candidato elegido es 13. Siguiendo el enunciado se debe hacer V - M para calcular la cantidad de votos a traspasar: 13 - 6 lo que da como resultado 7 votos a traspasar:)

![IMG_1127](https://user-images.githubusercontent.com/80866575/227728929-7b1e84bc-d2c8-4f17-a8ed-fe00b9af4f31.jpeg)

Mucho éxito!
