### ISSUE TITLE
T0 - Problemas con tests

### ISSUE THREAD

**Issue by t-munozp** [IIC2133-PUC/2023-1#43]
Hola! He tenido algunos problemas usando el servidor. Subí mi tarea el miércoles, corrí los test y estaban todos correctos. Subí una versión nueva para que no hubieran leaks y empecé con wrong outputs, así que volví a la versión original, pero sigo con wrong outputs en algunos.
He vuelto a correr el servidor tanto test como grade, y cada vez que lo corro tengo distintos wrong outputs (siempre en los tests C, varía entre easy y hard), y no he cambiado más el código. He verificado en VSCode comparando las soluciones con mi output y no hay diferencias entonces no entiendo qué está pasando :(
(Adjunto fotitos de mis tests)

<img width="600" alt="Captura de Pantalla 2023-03-24 a la(s) 20 57 58" src="https://user-images.githubusercontent.com/80847046/227664663-8429088b-672e-43bf-8b8e-4ce16096542d.png">
Al verificar comparando output con la solución easy-C0 (no hay diferencias en ninguna línea, se mostraría al lado derecho de la pantalla):
<img width="700" alt="Captura de Pantalla 2023-03-24 a la(s) 21 01 26" src="https://user-images.githubusercontent.com/80847046/227665178-b1d4c4ae-f2f1-4409-8d41-1b985ae914f3.png">

Muchas gracias de antemano!!

**Comment by sbersanii** [comment]
Hola! 
Me sumo a la duda, me arroja error el test c0 en grade, pero los resultados están bien en la logica.

![image](https://user-images.githubusercontent.com/56396783/227740641-1137b171-012a-4589-b811-ec9d65359dee.png)
