### ISSUE TITLE
T0-TRASPASAR-EXCESO-VOTOS

### ISSUE THREAD

**Issue by sbersanii** [IIC2133-PUC/2023-1#44]
Hola,
En esta parte cómo seleccionamos los votantes a traspasar? los de menor id ? o traspasamos los ultimos M - #_votos, no entiendo como priorizar ese traspaso.

Slaudos

**Comment by fddelabarra** [comment]
Hola,

Quizas la Issue #28 te pueda servir, si no lo hace, puedes volver a escribir por aqui.

Saludos!

**Comment by sbersanii** [comment]
Hola, no se habla del orden de traspaso de los votantes. Solo de a qué candidato se les traspasa.

**Comment by fddelabarra** [comment]
cuando hablas de orden de traspaso de los votantes te refieres a losque preguntan en la Issue #21 ?

**Comment by sbersanii** [comment]
Me refiero al evento TRASPASAR-EXCESO-VOTOS. Ahí la diferencia entre los votos del candidato electo con M se pasan a otro candidato. Pero cómo elijo los id de los votantes que traspasaré al otro candidato ? 
Ej: candidato 1 ganó y tiene a : voter 1, 5, 6 , 9

Y M es 2

Debo traspasar 2 votantes al otro candidato, cómo elegir a esos votantes 🙄

Gracias

**Comment by fddelabarra** [comment]
Tal como dice el enunciado, serian los ultimos M - #_votos, como explica el ejemplo

![image](https://user-images.githubusercontent.com/42189391/227679142-477134f2-bb06-4cc9-9f56-6ea09d18db25.png)

**Comment by sbersanii** [comment]
Vale, últimos agregados a ese candidato entonces. Gracias !
