### ISSUE TITLE
T0 - Ordenar candidato antes de pasar a parte C

### ISSUE THREAD

**Issue by nicolascamhi** [IIC2133-PUC/2023-1#46]
Hola! La forma que cree mi código es que crea los structs con los candidatos y sus votos en la función ordenar-candidatos. Necesito los structs para la parte C pero si en los codigos de prueba no se corre siempre ordenar-candidatos antes de pasar a trasferir los votos, no funcionará. Entiendo que no es el ideal pero ya lo tengo estructurado asi y no creo que tengo tiempo para rehacer el código completo. 

Quería saber si siempre se corre ordenar-candidato antes de pasar a transferir los votos.

**Comment by CarloGauss33** [comment]
Hola. No necesariamente. Quizas podrias copiar el array al momento de ejecutar ordenar. asi no te afecta el resto del programa
