### ISSUE TITLE
Diferencias Server Test y Local

### ISSUE THREAD

**Issue by nicolaspoli** [IIC2133-PUC/2023-1#47]
Hola! Estoy probando mi parte C con el archivo C0 de manera local con DiffChecker y me da correcto

![imagen](https://user-images.githubusercontent.com/69522096/227752968-7b022fa7-bf18-4efe-833c-88d9b879d5b8.png)

Pero luego en el server da incorrecto, y entiendo que es el mismo testcase

![imagen](https://user-images.githubusercontent.com/69522096/227753000-37bea297-2d42-42ac-8bf2-6fee9c0a2716.png)

Que podría estar pasado?

Gracias de antemano

**Comment by fddelabarra** [comment]
estas probando los test normales? o los test grade?

**Comment by nicolaspoli** [comment]
En los test normales

![imagen](https://user-images.githubusercontent.com/69522096/227781247-f994401f-3cc6-454c-bb27-a785980b7eac.png)

**Comment by CarloGauss33** [comment]
Y con diff -b. Probando con el C1?

**Comment by nicolaspoli** [comment]
Perdón, olvidé comentar que lo había solucionado, ya tengo todos los Test y los Grades buenos :D Gracias por sus respuestas
