### ISSUE TITLE
Preguntas sobre .gitignore y codigos externos

### ISSUE THREAD

**Issue by TMagini** [IIC2133-PUC/2023-1#48]
Holaa, tengo una consulta, respecto al `.gitignore`, me pasa que no modifique el que nos pasaron y me excluye la carpeta `src/dccars` por el parametro `dccars` en el archivo, entonces no se si dejar así la configuración o hacer la excepción con esa carpeta solamente, para que lo unico que se suba al repositorio sea:

- /src/dccars
- `.gitignore`
- Makefile
- README.md

no se si me faltaría algo que me este exluyendo el `.gitignore` o si lo dejo así.

Mi otra pregunta va relacionada a la citación de codigo de terceros. Basta con colocar en las partes del codigo que la información la saque de X página o que me base de tal capsula o tal presentación o hay alguna regla de especificarlo en el README o algun otro archivo?

Gracias de antemano.

**Comment by CarloGauss33** [comment]
1. Hace una excepcion. Con las carpetas que mencionas todo esta OK.

2. Dejalo en el Readme. Hay una seccion para dejar enlaces a referencias
