### ISSUE TITLE
Problemas con gitignore

### ISSUE THREAD

**Issue by piriabud** [IIC2133-PUC/2023-1#49]
Hola, igual que la issue anterior también estoy teniendo problemas para subir mis archivos al repositorio. Tengo todos mis structs declarados en `struct.h` y definidos en `struct.c`, sin embargo cuando hago `git push` ninguno de los archivos es tomado en cuenta para ser subido al repo. Anteriormente, en la misma ubicación tenía 4 archivos `voter,h`, `voter.c`, `candidate.h` y `candidate.c` que sí eran considerados en mis `git push`.

La distirbución local de las carpetas en mi repositorio `T0-2023-1-piriabud` es:
```
> obj
> solutions
> src\dccars
    > main.c
    > struct.c
    > struct.h
> tests
.gitignore
dccars
Makefile
README.md
rutests.sh
```
En mi .gitignore tengo:
```
*.txt
tests/
solutions/
run_tests.sh
obj/
dccars
```

**Comment by CarloGauss33** [comment]
Holaaa. Toda la razón. Gracias por avisar. sii,  elimina dccars desde el gitignore.
