### ISSUE TITLE
T0 - Modularización

### ISSUE THREAD

**Issue by kalarconvl** [IIC2133-PUC/2023-1#5]
Hola!!
Estoy un poco confundida con el orden de los archivos en las carpetas y la modularización del programa. Nos entregaron:
`T0`
`  src`
`    dccars`
`      main.c`
`  Makefile`
`  README.md`

¿Puedo agregar carpetas dentro de `src`? Por ejemplo, una carpeta `hellofile` que contenga los archivos de código encargado de leer el input:
`T0`
`  src`
`    dccars`
`      main.c`
`    hellofile`
`      read_input.c`
`  Makefile`
`  README.md`

¿Eso sería correcto?, ¿o todo debe ir dentro de `dccars`? ¿El makefile se supone que lee la modularización que yo haga?

Y sobre el input/output: ¿dónde se supone que estará almacenado? ¿y donde debe quedar almacenado el txt con el output?

**Comment by CarloGauss33** [comment]
@kalarconvl Hola!. Si se puede, aunque implicaria modificar el makerfile para que de esa forma se compile dicha carpeta como libreria. 
En general, la convención es que solo se deja en carpetas separadas cuando es un "módulo" separado
En caso contrario si solo es para separar los archivos puede ser: (esto es lo mas simple para el contexto de este curso)
```
T0
  src
    dccars
      main.c
      read_input.h
      read_input.c
  Makefile
  README.md
```
> ¿Eso sería correcto?, ¿o todo debe ir dentro de dccars? ¿El makefile se supone que lee la modularización que yo haga?
Cuando se compila DCCars, lo que hace el compilador es que busca el archivo main.c desde donde importas todos los archivos adicionales. Por lo que para modularizar basta con lo descrito antes

> Y sobre el input/output: ¿dónde se supone que estará almacenado? ¿y donde debe quedar almacenado el txt con el output?
Idealmente deberia ir a la misma altura que el makefile por ejemplo:
```
T0
  src
    dccars
      main.c
    hellofile
      read_input.c
  tests/
      test_1.txt  
  Makefile
  README.md
```

Esto porque al compilar con `make` se generara un ejecutable en dicha ruta, y por ende es mas facil ejecutarlo ahi mismo con los tests facilmente accesibles
