### ISSUE TITLE
Usuario inexistente

### ISSUE THREAD

**Issue by cristhanos** [IIC2133-PUC/2023-1#50]
![image](https://user-images.githubusercontent.com/101376517/227793195-bdf824ab-5ac3-4795-9210-2f9a149ec4f3.png)
@cparedesr 
Hola, feliz de que alguien me ayude!

**Comment by CarloGauss33** [comment]
Hola! habia un typo en el username que habias configurado. Actualizado. Ahora deberias poder usar bien el servidor
