### ISSUE TITLE
Tiempos de ejecucion inconsistentes en el servidor

### ISSUE THREAD

**Issue by FranciscoPintoo** [IIC2133-PUC/2023-1#51]
Tiempos de ejecución inconsistentes en el servidor

Hola tengo una duda con respecto a los tiempos de ejecución en el servidor.
Hace un par de días probé mi código en el servidor en formato grade y pase todos los testcase, hoy volvi a probar y algunos testcase me dieron timeout error. Entonces volví a probar y ahora los estaba pasando todos. Pero me di cuenta que el tiempo que demoran es muy distinto por cada intento que hago. No cambie en nada el código entre los 5 intentos, sin embargo tengo diferencias de más de 4 segundos en algunos test.

No tomé captura del primer intento, pero recuerdo que el test más largo me tomó aproximadamente 7 segundos.

Y acá tengo capturas de 4 intentos con el mismo código base donde se puede ver que para tests grandes los tiempos varían en hasta 3-4 segundos por intento

![image](https://user-images.githubusercontent.com/69857506/227801148-13077357-3fa7-4fcc-b38e-66475f83510e.png)
![image](https://user-images.githubusercontent.com/69857506/227801177-ef2a144a-7a39-4c0b-b5f9-6f5f95d19f80.png)
![image](https://user-images.githubusercontent.com/69857506/227801195-97f0ca1c-9b13-4c7c-bb06-8c21cd241958.png)

![image](https://user-images.githubusercontent.com/69857506/227801858-a6bf98b9-9c44-46f0-9715-e5c7aa8b3834.png)

Tengo 2 preguntas:
¿Por qué puede estar variando tanto los tiempos de ejecución? 
¿Para la corrección como funcionan estos casos, se prueban varias veces los códigos o es al primer intento?

**Comment by fddelabarra** [comment]
- Los tiempos de ejecucion aveces depende de que tan cargado esta el servidor (normalmente los ultimos dias de la entrega mucha gente prueba su tarea, lo que lo ralentiza), pero no te preocupes, cuando se revisa la tarea se hace con un computador más potente así que no debes preocuparte.

- Igual en caso de algun problema con el TimeOut cuando te entreguen la nota, siempre puedes recorregir (:
