### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by nicolascamhi** [IIC2133-PUC/2023-1#55]
Hola! Me inscribieron el ramo tarde asi que tengo un par de días más de plazo para la T0. Quería preguntar cómo se puede arreglar un segmentation fault y porqué pasa. Me da ese error cuando el programa ya está compilado y trato de ejecutarlo con ./dccars input output

**Comment by Pakarati** [comment]
Hola! Los segmentation fault pueden ocurrir por diversos errores, no necesariamente uno en específico (recomendado usar Valgrind para saber que sucede). En tu caso, puede ser que no te esté abriendo bien el archivo input, ya que deberías escribir `./dccars input.txt output.txt` agregando la extensión. Recuerda también revisar que le estés pasando bien la ruta del input (si no está en el root de tu tarea, entonces debes agregar la carpeta en la que se encuentre)

Mucho éxito!
