### ISSUE TITLE
T1 - Problemas con #include <cairo.h>

### ISSUE THREAD

**Issue by tomasernst** [IIC2133-PUC/2023-1#56]
Hola, tengo un problema con la librería `cairo.h` y supongo que es porque al tratar de instalar libjpeg-dev me dice que no existe. ¿Es ese el problema o qué estoy haciendo mal?

![image](https://user-images.githubusercontent.com/80714248/231230491-8b290e13-17a9-4325-8c78-be4bcf5f35e3.png)

![image](https://user-images.githubusercontent.com/80714248/231230276-142c1ab1-375e-4c68-b70f-e646c68ce410.png)

**Comment by CarloGauss33** [comment]
Intenta con `brew install jpeg`

**Comment by tomasernst** [comment]
Sigue tirando error. Dentro del docker me funciona bien como dijiste.

**Comment by angelescox** [comment]
Yo igual tengo problemas con este y con el #include <gtk/gtk.h>, que tengo que hacer? he tratado de instalar muchas cosas y no se me sale. Yo estoy en windows, no mac

**Comment by pureyesz** [comment]
Tengo el mismo problema, estoy en Mac

**Comment by CarloGauss33** [comment]
Hola! Deje una solucion mas completa en esta issue:
https://github.com/IIC2133-PUC/2023-1/issues/64#issuecomment-1509475848
