### ISSUE TITLE
T1 - duda con qsortcars

### ISSUE THREAD

**Issue by sachondo7** [IIC2133-PUC/2023-1#57]
Hola, en el enunciado de la parte 2, nos dicen que nos entregan N que al final sería el numero de autos a ordenar. Sin embargo, en el ejemplo se supone que se piden 4 autos pero finalmente son 6 los que se ordenan. Está malo? Deberían ser 4? o 5 si se comienza del 0?

**Comment by VichoAburto** [comment]
Tengo la misma duda🧐🧐

**Comment by a-ck** [comment]
Me uno a la duda y aprovecho a hacer otra relacionada con esto: asumimos que siempre nos entregarán los N autos en orden de id? o sea si N=3 nos pasarán en orden el 1, 2 y 3 o podría ser que los entreguen como 2, 3 y 1 por ejemplo?
