### ISSUE TITLE
[T1] - Duda con INVERT + DEEP-ORDER

### ISSUE THREAD

**Issue by aboehmg** [IIC2133-PUC/2023-1#59]
¡Hola! Tengo una duda cuando ocurre un INVERT y luego un DEEP-ORDER. Por lo que entiendo del enunciado, luego de que hay un INVERT el árbol queda "invertido", por lo que ahora los nodos izquierdos son nodos derechos y viceversa. Además, entiendo que esta inversión se preserva. Si después ocurre un DEEP-ORDER yo entiendo que se debiera imprimir lo mismo que se imprimió luego de que sucedió el INVERT. Dicho eso, en el ejemplo no ocurre esto y me interesa saber por qué.
A continuación se muestran en negrita las partes que no me hacen sentido:

4
51 414 23 104
12
PATH 10
DEEP 104
PATH 104
DEEP-ORDER
ORDER
**INVERT**
PATH 10
DEEP 104
PATH 104
**DEEP-ORDER**
ORDER
INVERT

51 23 X
2
51 414 104
51 23 414 104
23 51 104 414
**51 414 23 104**
51 23 X
2
51 414 104
**51 23 414 104**
23 51 104 414
51 23 414 104

¡Gracias de antemano!

**Comment by Baelfire18** [comment]
No, ese es el truco, el `DEEP-ORDER` debe imprimir el orden en profundidad del árbol independiente si está invertido o no. Por lo mismo debes chequear si está invertido y de estarlo, ordenar ese piso o nivel
