### ISSUE TITLE
T0 - Traspaso de votos

### ISSUE THREAD

**Issue by aboehmg** [IIC2133-PUC/2023-1#6]
¡Hola! Leyendo el enunciado no me quedan claras ciertas funcionalidades del traspaso de votos:
1. Al momento de un conteo parcial, ¿es necesario mostrar los votos por candidato en algún orden específico (estoy asumiendo que se entregan en orden los votos, por como se muestra en el enunciado)? Esto es relevante, dado que, cuando se traspasan votos de un candidato a otro, estos podrían quedar en un orden no deseado.
2. ¿Luego de un traspaso de votos (por eliminación o por declaración de ganador) pueden seguir llegando votos? Si es que la respuesta es sí, ¿los votos siguientes a qué candidato le llegan?

¡Gracias de antemano!

**Comment by CarloGauss33** [comment]
Hola! 
1. Solo en orden de llegada. La idea es que si es que llega un voto de id 5 y luego otro de id 10. Se muestren en ese orden. Y por ejemplo si luego se le transfieren votos con ids 1 y 2. deberia mostrar 5 -> 10 -> 1 -> 2.
2. No, no seguiran llegando votos luego de que se elimina un candidato
