### ISSUE TITLE
T1 - Duda con código preestablecido qsortcars/main.c

### ISSUE THREAD

**Issue by a-ck** [IIC2133-PUC/2023-1#60]
Hola! En el código del main venía en la línea 33: `char** cars = malloc(N * sizeof(char*));`. Esto significa que estamos obligados a guardar los autos en esa variable cars? También quería saber si podíamos borrar la línea 37: `printf("%f %f %f %f", id, model, average_lap_time, victory_count);` ya que me parece irrelevante. Desde ya gracias.

**Comment by Baelfire18** [comment]
Borro la línea 33 completamente no más. Fue un error de último minuto

**Comment by a-ck** [comment]
ya ok gracias! y la 37?

**Comment by Baelfire18** [comment]
Es un print no más, así que queda a tu criterio si lo dejas o lo borras, eso no se revisa
