### ISSUE TITLE
T1 - Guía instalación GTK+3 caída

### ISSUE THREAD

**Issue by ignaciaurrutia** [IIC2133-PUC/2023-1#61]
Hola, el link de la guía de instalación del programa GTK+3 está caído.

**Comment by Baelfire18** [comment]
Este link?
https://github.com/IIC2133-PUC/2023-1/blob/master/Gu%C3%ADas/Set%20Up/3.0%20(Extra)%20GTK.md

**Comment by ignaciaurrutia** [comment]
Sí, gracias! Apretándolo desde el enunciado sale "Page not found", parece que el link es  del 2022.

**Comment by Baelfire18** [comment]
@ignaciaurrutia ahí actualicé el link del enunciado
