### ISSUE TITLE
T1 - Cantidad de decimales en Parte 2

### ISSUE THREAD

**Issue by aboehmg** [IIC2133-PUC/2023-1#63]
¡Hola nuevamente! ¿La cantidad de decimales a imprimir siempre será la misma en el output de la parte 2 (1, 4, 1 y 1 para id, model, lap_time, victories respectivamente)? Gracias de antemano.

**Comment by camirojasguajardo** [comment]
me sumo a la pregunta

**Comment by CarloGauss33** [comment]
Hola! Sip, pueden verificarlo en los archivos de output esperado
