### ISSUE TITLE
Problemas descarga GTK

### ISSUE THREAD

**Issue by angelescox** [IIC2133-PUC/2023-1#64]
No puedo descargarme gtk, he buscado mucho y en todo me tira error, errores de 404 "Not found", fail to fetch, cuando se esta descargando, entonces no puedo compilar la tarea ni para hacer la parte 1.

**Comment by Baelfire18** [comment]
- Para ayudarte necesitamos más detalles, tal como tu sistema operativo donde intentas correrlo (W10, W11, Mac, Linux, WSL, etc)
- Una forma en la que si o si te debería funcionar es utilizando docker para correr tu tarea. [Puedes ver como hacerlo acá](https://github.com/IIC2133-PUC/edd-docker)
- Por último, si quieres empezar rápido y sin problemas puedes cambiar en el `Makefile` la línea 55 y 56 y dejarlas así:
```make
# Directorios que serán compilados a un programa
PROGRAMS=qsortcars bstmate
```
Esto elimina la acción de compilar la parte 3.

**Pero ten en cuenta que para realizar la parte 3 deberás dejarla como estaba antes. Esta es una solución *parche y rápida* para realizar las otras partes sin mayores contratiempos**

**Comment by angelescox** [comment]
Tengo W11, pero lo estoy intentando correr en WSL

**Comment by CarloGauss33** [comment]
@angelescox que output te da la terminal al hacer `sudo apt-get update && sudo apt-get upgrade`?

**Comment by angelescox** [comment]
Ahi si! Creo que ahi si se descargo bien, osea despues de ese comando, puse los comandos de la guia de instalacion y no hubo errores, pero al tratar de compilarlo (make), me sale este error ahora:
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
make: *** [Makefile:129: simulate] Error 1

**Comment by CarloGauss33** [comment]
@angelescox 
en la linea 56 del makefile, cambiala por esto:

`PROGRAMS=visualizer_core qsortcars kdtree bstmate`

Elimina simulate

**Comment by angelescox** [comment]
Uu sii, graacias!!

**Comment by camirojasguajardo** [comment]
Hola! tengo un error similar, en wsl en Windows 10. Mi makefile ya tenía la línea 56 como indicaste jiji (creé hoy el repo). 

Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
compiled 'obj/engine/math/geometry.o'
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
compiled 'obj/engine/math/vector.o'
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
compiled 'obj/engine/particle.o'
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
compiled 'obj/visualizer/visualizer.o'
Package gtk+-3.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `gtk+-3.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gtk+-3.0' found
In file included from src/visualizer_core/animating/animation.c:1:
src/visualizer_core/animating/animation.h:3:10: fatal error: gtk/gtk.h: No such file or directory
    3 | #include <gtk/gtk.h>
      |          ^~~~~~~~~~~
compilation terminated.
make: *** [Makefile:119: obj/visualizer_core/animating/animation.o] Error 1

**Comment by Baelfire18** [comment]
@camirojasguajardo probaste con `sudo apt-get update && sudo apt-get upgrade` ?

Y luego el resto de comandos para descargar GTK

**Comment by CarloGauss33** [comment]
Lo dejo en la issue para que quede tmb:
En general hartos errores son por tener los gestores de paquetes desactualizados. Con lo siguiente se puede arreglar:
WSL o Linux:

`sudo apt-get update && sudo apt-get install libgtk-3-dev`

Mac:
Si tienen ese mismo problema en mac, puede que se deba a exactamente lo mismo (Que su manager de paquetes este desactualizado). Lo pueden arreglar asi:

`brew update && brew install gtk+ && brew install gtk+3 && brew install jpeg`
En caso de que el problema siga:



```
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch 
brew update
brew install jpeg
brew install gtk+
```

**Comment by camirojasguajardo** [comment]
> @camirojasguajardo probaste con `sudo apt-get update && sudo apt-get upgrade` ?
> 
> Y luego el resto de comandos para descargar GTK

volví a ejecutar este comando y funcionó! graciasss

**Comment by BMagasich** [comment]
Hola corrí los códigos que salen arriba y me sigue apareciendo 

"fatal error: 'cairo.h' file not found
#include <cairo.h>"

Estoy en Mac

**Comment by CataAlamos** [comment]
Hola! Lo mas probable es que no tengas installado cairo, te sugiero hacer ` brew install cairo` ! Avisa como te va

**Comment by BMagasich** [comment]
Hola! ya había corrido ese código y no pasa nada. 
Revisé y tengo instalado todo lo que se pedía en el setup, nose por que me sigue tirando el mismo error
<img width="698" alt="Captura de Pantalla 2023-04-18 a la(s) 18 19 45" src="https://user-images.githubusercontent.com/89421238/232917639-dbd797a6-7855-4e08-91d9-3e1805d95abc.png">

**Comment by CataAlamos** [comment]
Me puedes mostrar que te dice cuando haces el brew install?

**Comment by BMagasich** [comment]
<img width="560" alt="Captura de Pantalla 2023-04-18 a la(s) 18 22 08" src="https://user-images.githubusercontent.com/89421238/232917950-e00d530f-5236-4f23-87e2-5595d5d501f9.png">

**Comment by CataAlamos** [comment]
Y si le haces el reinstall?

**Comment by BMagasich** [comment]
ya lo hice y no pasa nada

**Comment by CataAlamos** [comment]
Tienes tiempo para que lo veamos en el discord?

**Comment by BMagasich** [comment]
si!

**Comment by CataAlamos** [comment]
Ve a la sala 0

**Comment by tomasernst** [comment]
Lo pudieron arreglar? Tengo el mismo problema

**Comment by CarloGauss33** [comment]
@tomasernst Tienes Mac M2 de casualidad? una solucion es utilizar edd docker para compilar. Ya que el visualizador es solamente decorativo. Puedes hacer tu tarea sin necesidad de el

**Comment by tomasernst** [comment]
Si, tengo Mac con M2.
Lo estaba haciendo con el docker, pero pensé que eventualmente iba a poder ocupar el visualizador para entender mejor el problema. De igual forma gracias!

**Comment by CarloGauss33** [comment]
Lamentablemente M2 tiene un problema con los paths en brew que aun no ha sido resuelto. Estamos buscando workarounds pero aun no hemos encontrado nada
