### ISSUE TITLE
T1 - Duda de Enunciado Parte 1

### ISSUE THREAD

**Issue by amandaarod** [IIC2133-PUC/2023-1#65]
Holaa, tengo una duda sobre la repetición del valor de los nodos, ya que en el Hint de la parte 1 dice que **en empate de valores, hay que hacerlo por orden de input** que asumo se refiere al valor de los nodos. Pero en el inciso de Input y Output de la misma parte, dice que **no se entregaran nodos repetidos**. Entonces, mi duda es que si hay que ignorar esa parte del hint o se refiere a otra cosa?

**Comment by Baelfire18** [comment]
En los tescases no habrá nodos repetidos, así que no importa si manejas las repeticiones

**Comment by Baelfire18** [comment]
@amandaarod el enunciado acaba de ser actualizado 😁

**Comment by amandaarod** [comment]
ya! muchas gracias:) y otra duda en relación al mismo problema que me surgió recién. ¿Podemos asumir que nunca se entregará un input vacío? Es decir, que siempre tendremos al menos un elemento raíz?

**Comment by Baelfire18** [comment]
Sip

**Comment by amandaarod** [comment]
fino, graciaaas
