### ISSUE TITLE
T1 - Tests quicksort

### ISSUE THREAD

**Issue by Gazteka** [IIC2133-PUC/2023-1#66]
Holaa, parece que los tests de la parte del quicksort tienen un error porque están sin formato y no siguen la estructura del enunciado

Se ven asi :  
<img width="737" alt="Captura de pantalla 2023-04-15 075112" src="https://user-images.githubusercontent.com/65355948/232217655-b7077f34-0264-4cda-91c6-c8db63601025.png">

**Comment by CarloGauss33** [comment]
Modificados los tests! Gracias por avisar
