### ISSUE TITLE
T1 - Parte 3 - Segmentation fault: Process terminating with default action of signal 13 (SIGPIPE)

### ISSUE THREAD

**Issue by camibennett** [IIC2133-PUC/2023-1#67]
Hola! Me esta saliendo el error "Segmentation fault: Process terminating with default action of signal 13 (SIGPIPE)" que parte en la linea 28 del archivo main.c ("Simulation *sim = simulation_init_from_file(argv[1], visualize);") y no entiendo a que se debe, ya que no cambie nada antes de esa linea en el main.c ni de los otros archivos que salen en el error de valgrind. 

Que puede ser? 
Muchas gracias de antemano!

**Comment by CarloGauss33** [comment]
Update: El error era que al ejecutar en valgrind (dentro de docker), debe ir la flag --novis en la parte 3 de la tarea:

Por ejemplo

`valgrind ./kdtree input output --novis`

Por si tienen curiosidad. El error era un SIGPIPE la cual es una señal que se emite cuando algo paso mal en el pipe entre un proceso y otro. En particular visualizer core invoca a librerias de sistemas para enviar bits que permiten la visualización. Como el engine de visualizacion en docker esta apagado, y valgrind no sabe eso. Se encuentra enviando los datos a un target que no existe y genera la señal.
