### ISSUE TITLE
Include de archivos en otras carpetas

### ISSUE THREAD

**Issue by piriabud** [IIC2133-PUC/2023-1#68]
Hola, estoy tratando de llamar desde `main.c` a un `structs.h` donde tengo definidos mis structs. En detalle la distribución de las carpetas es:
```
T1-2023-1-piriabud
    src
        bstmate
            main.c
        structs
            structs.c
            structs.h
```
Actualmente lo estoy llamando desde `main.c` con la siguiente linea (que según lo que he leído es correcto):

`#include "../structs/structs.h"`

Sin embargo, cuando intento correr el `make` me arroja el siguiente error
```
/home/eabud/T1-2023-1-piriabud/src/bstmate/main.c:139: undefined reference to `create_node'
/usr/bin/ld: /home/eabud/T1-2023-1-piriabud/src/bstmate/main.c:144: undefined reference to `create_node'
/usr/bin/ld: /home/eabud/T1-2023-1-piriabud/src/bstmate/main.c:145: undefined reference to `insert_node'
collect2: error: ld returned 1 exit status
make: *** [Makefile:126: bstmate] Error 1

```
En resumen, las funciones que tengo declaradas en `structs.h` y definidas en `structs.c` no están siendo referenciadas en el `main.c,` asumo que el problema está en cómo incluyo el archivo. Eso, gracias.

**Comment by CarloGauss33** [comment]
Si quieres estructurarlo asi, debes agregar strucs al makefile. De esa forma los archivos seran compilados

**Comment by CarloGauss33** [comment]
Igualmente viendo que son structs especificas a bstmate. Puedes dejarl como
```
bstmate/
   main.c
   structs/
      .....
```

**Comment by robertoorrego** [comment]
Al estructurarlo así igual hay que editar el makefile? O solo habría que editarlo si se hiciera una carpeta Structs que contenga todos los structs que sean necesarios para todas las partes de la tarea (como lo hizo el que abrió el issue)?
