### ISSUE TITLE
T0 - tabs en output

### ISSUE THREAD

**Issue by denisseleiva** [IIC2133-PUC/2023-1#7]
Hola! Al escribir el output estoy usando `\t` para hacer los tabs, pero parecieran ser más grandes que los del enunciado. ¿Cuál es el tamaño de tab que hay que usar? Porque me imagino que la corrección automática va a tomar en cuenta eso también

**Comment by CarloGauss33** [comment]
Esta bien utilizar \t. Deberia ser el equivalente a 4 spaces

**Comment by kalarconvl** [comment]
Hola!! Me sumo a esta pregunta. Cuántos tabs hay que usar para cada parte? Por ejemplo, en el test easy A0 la solución es:
```
CONTEO-PARCIAL
	CANDIDATE 0
		VOTE 0
	CANDIDATE 1
		NO HAY VOTOS REGISTRADOS
```
¿Antes de `CANDIDATE` va 1 tab: `\t`; y antes de `VOTE voter_id` o de `NO HAY VOTOS REGISTRADOS` van 2 tab: `\t\t`?
