### ISSUE TITLE
Problema al compilar

### ISSUE THREAD

**Issue by ignaciovial01** [IIC2133-PUC/2023-1#70]
Hola! No puedo compilar el código. Solo he modificado el main de la parte 1 y creado un archivo nodo.c y nodo.h. Al utilizar el comando make me tira el siguiente error:
![imagen](https://user-images.githubusercontent.com/89284931/232263416-a1273e3a-d8bc-445e-9575-142660b78d20.png)

Estoy utillizando Windows 11 con wsl y seguí la guía del curso para instalar GTK.

**Comment by amondinellir** [comment]
Hola. A mi me pasa lo mismo y no se que puedo hacer.

**Comment by Pakarati** [comment]
Hola! @amondinellir @ignaciovial01
En caso de que hayan creado sus repos antes de 13 de abril, puede que aún tengan en la línea 56 del makefile "simulate". Prueben borrando eso.
