### ISSUE TITLE
Duda output parte 2

### ISSUE THREAD

**Issue by ignaciovial01** [IIC2133-PUC/2023-1#72]
Hola! Tengo una duda acerca de como se debe ordenar por número de victorias. En el enunciado están en orden descendente: 

![imagen](https://user-images.githubusercontent.com/89284931/232361242-b55909b0-f749-425b-833e-9ca0756f4908.png)

 pero en los tests están en orden ascendente:

![imagen](https://user-images.githubusercontent.com/89284931/232361308-509921b8-08d5-4be9-8273-0c924784816c.png)

¿Cuál formato debo respetar?

**Comment by amondinellir** [comment]
Tengo la misma duda. No se como deba ordenarlos.
