### ISSUE TITLE
T1 - Memory leaks en parte 3?

### ISSUE THREAD

**Issue by jtmeyer98** [IIC2133-PUC/2023-1#78]
Hola!! Antes de comenzar a escribir código de la parte 3 quise comprobar que estuviera todo bien, pero al parecer el código entregado viene con leaks de memoria. Esto se ve al correr `valgrind ./kdtree tests_kdtree/tests/test_01.txt output.txt`

![image](https://user-images.githubusercontent.com/37156969/233206141-49ab7be2-4b6f-4edf-b0ff-fcfdae74855f.png)

Esto significa que hay leaks de memoria? o esta todo bien y no hay que preocuparse?

**Comment by amondinellir** [comment]
Me pasó lo mismo, no se como solucionarlo.

**Comment by CarloGauss33** [comment]
Ejecuten con `--novis` al final. Lo que ocurre es que valgrind esta tratando de abrir el visualizador, y eso genera problemas de tratatar de escribir en el mismo
