### ISSUE TITLE
T1 - Parte 3 - Dudas de conceptos

### ISSUE THREAD

**Issue by amondinellir** [IIC2133-PUC/2023-1#79]
Hola. Estoy teniendo problemas para entender la parte 3. Primero, no entiendo que son los segmentos. Sé que tienen un vector inicial y uno fnal pero no sé que representan. Y segundo, no logro entender qué es lo que debemos dejar del programa y qué modificar. Ya he visto que en la tarea describen algunas funciones de "visualizer" y "engine", pero no se que se necesita utilizar.

Espero que me puedan ayudar. Gracias.

**Comment by CarloGauss33** [comment]
Hola! La idea de la tarea es que optimices el código ya existente para que su tiempo de ejecución pase dé. O(FPS) a O(FP los(S))

Un segmento está descrito por dos puntos. Representan una "pared" donde las partículas pueden rebotar. 

Debes modificar lo que está dentro de la carpeta kdtree. Visualizer y engine no deberías tener que tocarlos. La idea es que implementes un KDTREE donde mejores la eficiencia de encontrar los segmentos donde vale la pena revisar si hay o no colisión
