### ISSUE TITLE
T0 - Conteo Parcial después de eliminar candidato

### ISSUE THREAD

**Issue by MTaisa** [IIC2133-PUC/2023-1#8]
Holaa, una pequeña duda, si después de eliminar a un candidato se recibe un evento de CONTEO-PARCIAL, los votos que estaban registrados con un ID del candidato anterior deben cambiarse al ID del nuevo candidato, alterando así el voto, o se transfiere la cantidad de votos del eliminado y el voto se mantiene sin alterar ?? Lo digo porque no sabría muy bien como funcionaría el CONTEO-PARCIAL una vez que se elimina un candidato.

**Comment by CarloGauss33** [comment]
En efecto se alterarian los votos. La idea es que realmente se transfieran los votos y no sea solamente un cambio en el numero
