### ISSUE TITLE
T1 - Invertir árbol (o no) -  Parte 1

### ISSUE THREAD

**Issue by andresmoraga0** [IIC2133-PUC/2023-1#80]
Hola!

Cuando nos piden invertir el árbol, realmente es necesario modificarlo? En mi caso por lo menos, de una forma particular, lo imprimo inviertido cada vez que lo necesito, sin realmente modificarlo. 

Los tests funcionan perfecto, en cuanto a output, tiempo y memoria. Mi duda es escencialmente si alguien se va a meter a revisar si efectivamente modifiqué el árbol 😅 y en caso de que no lo esté, si es eso correcto.

Muchas gracias.

**Comment by CarloGauss33** [comment]
Hola. Si tu codigo funciona. ningun problema con tu implementación. Solamente se "revisa" algo explicitamente en caso de que se prohiba su uso (Por ejemplo alguna funcion de sorting built in o cosas de ese estilo)

TLDR; Ningun problema, mientras te funcione todo OK
