### ISSUE TITLE
Correr tests en local

### ISSUE THREAD

**Issue by vice-rosas99** [IIC2133-PUC/2023-1#81]
Hola pregunto su hay algún archivo o alguna forma de correr tests específicos o grupos de tests localmente, para la tarea pasada nos entregaron un archivo run_tests.sh pero ese archivo solo funciona con la tarea 0 y sus directorios.

**Comment by Baelfire18** [comment]
@vice-rosas99 hola, todos los testcases estan subidos en googledrive en la carpeta compartida por anuncio de canvas.

En cuanto al archivo sh, no hay uno oficial entregado por ayudantes pero dado el entregado en la Tarea 0 y con los testcases de esta tarea tu puedes crear uno por tu cuenta.

Igual si te metes [al telegram del curso](https://ccc.ing.puc.cl/cursos/) y revisar los archivos enviados podrás ver que un compañero tuyo ya hizo un `run_tests.sh` para las 3 partes de esta tarea

**Comment by vice-rosas99** [comment]
ok, pero al correrlos directamente necesito ver si el output de mi tarea es igual al de la solucion. Para el caso de la solucion de los tests hard, al intentar abrirlos, la aplicación no me muestra el contenido en texto simple, sino en texto con símbolos, entonces no puedo hacer la corrección al ojo, vi que subieron una herramienta eddcmp que parece que sirve para comparar dos archivos sin abrirlos, pero no estoy seguro.

**Comment by CarloGauss33** [comment]
Para comparar dos archivos puedes usar `diff -b archivo_original archivo_target` y eso imprime todas las diferencias (eddcmp es solo para correjir, ya que no dice cuales son las diferencias, solo dice si son o no diferentes)
