### ISSUE TITLE
Error al compilar

### ISSUE THREAD

**Issue by PaulaCoronado** [IIC2133-PUC/2023-1#82]
![Captura de Pantalla 2023-04-22 a la(s) 21 20 56](https://user-images.githubusercontent.com/42159693/233814192-40fa1481-b9aa-4a5b-908f-6b93eac88d21.png)

Hola! Tengo este error, ¿ Por qué será?

**Comment by fcbahamondes** [comment]
Tengo el mismo error!!

**Comment by ferperezh** [comment]
Yo igual y corri todas las librerias que nos pedian
