### ISSUE TITLE
T1 - Error con Makefile Parte 3

### ISSUE THREAD

**Issue by ignaciaurrutia** [IIC2133-PUC/2023-1#83]
Hola, me tira el siguiente problema cuando trato de correr la parte 3. 

![image](https://user-images.githubusercontent.com/80770528/233870773-d4a57e12-4b30-4259-9188-0eb5ffceff25.png)

Ya arreglé el Makefile en la línea 56 para que dijera PROGRAMS=visualizer_core simulate qsortcars kdtree bstmate, así que no sé qué puede estar fallando ahora.

**Comment by ignaciaurrutia** [comment]
Logré resolverlo usando /.kdtree en vez de /.simulate. Se puede hacer eso o cuando corren el programa para corregirlo debería llamarse /.simulate el archivo?

**Comment by Baelfire18** [comment]
> Logré resolverlo usando /.kdtree en vez de /.simulate. Se puede hacer eso o cuando corren el programa para corregirlo debería llamarse /.simulate el archivo?

Revisa un anuncio en canvas donde se aviso que deberias cambias borrar kdtree y cambiar el nombre de simulate a kdtree.

Pero se revisa en el server con `./kdtree`
