### ISSUE TITLE
T1 - parte 3. No puedo correr ./kdtree 

### ISSUE THREAD

**Issue by BMagasich** [IIC2133-PUC/2023-1#84]
intento correr la parte 3 con los test demo para corroborar que funcione el visualizador, pero me tira el siguiente error.
<img width="1170" alt="Captura de Pantalla 2023-04-23 a la(s) 20 33 23" src="https://user-images.githubusercontent.com/89421238/233875736-98a043f9-1095-428a-b0a6-c3f72c1156c2.png">

**Comment by Baelfire18** [comment]
1. Asegurate que la distribución de la parte 3 sea la correcta. Es decir tengas una carpeta kdtree y no tengas una carpeta simulate. [Debe estar de esta forma](https://github.com/IIC2133-PUC/Base-T1-2023-1)
2. Puede ser que la ruta sea incorrecta. Te recomiendo fuertemente usar rulas relativas y no absolutas, es decir, pon la ruta desde donde etas hasta el archivo.

**Comment by BMagasich** [comment]
Hola, sigo con el mismo error
