### ISSUE TITLE
Conflicto Server v/s Solutions

### ISSUE THREAD

**Issue by jigodoy** [IIC2133-PUC/2023-1#85]
Hola! Hice la parte 2 (quicksort), y cuando comparo mi output con la solución esperada de varios tests, no tengo problemas (usé diffchecker y diff), pero cuando ocupo el server me dice WRONG OUTPUT en todos los tests.

**Comment by Baelfire18** [comment]
@jigodoy acabo de clonar tu tarea y no es así.

Por ejemplo en el test easy_a.txt, la respuesta esperada es:
```
3.0 6.1169 5.6 6.0
8.0 2.6191 6.8 6.0
7.0 4.3941 4.4 5.0
10.0 5.2405 5.6 5.0
9.0 8.7571 4.1 3.0
1.0 2.2318 5.1 3.0
2.0 6.6369 5.1 3.0
4.0 6.6369 5.1 3.0
5.0 8.7243 5.9 1.0
6.0 1.8966 6.3 1.0
```
y tu respondes:
```
5.0 8.7243 5.9 1.0
6.0 1.8966 6.3 1.0
9.0 8.7571 4.1 3.0
1.0 2.2318 5.1 3.0
2.0 6.6369 5.1 3.0
4.0 6.6369 5.1 3.0
7.0 4.3941 4.4 5.0
10.0 5.2405 5.6 5.0
3.0 6.1169 5.6 6.0
8.0 2.6191 6.8 6.0
```
lo cual es incorrecto

**Comment by jigodoy** [comment]
Oka, igual revise mis tests y aparece que la solución correcta para el testcase easy_a.txt es 

5.0 8.7243 5.9 1.0
6.0 1.8966 6.3 1.0
9.0 8.7571 4.1 3.0
4.0 6.6369 5.1 3.0
2.0 3.9682 5.3 3.0
1.0 2.2318 6.9 3.0
7.0 4.3941 4.4 5.0
10.0 5.2405 5.6 5.0
3.0 6.1169 5.6 6.0
8.0 2.6191 6.8 6.0

No se a que se debe pero cambiare el codigo al tiro. Gracias

**Comment by Baelfire18** [comment]
revisa los testcases del drive, es posible que tu haya sobreescrito las respuestas correctas en tu compu sin darte cuenta y no eso te aparecen las tuyas "iguales a las correctas"
