### ISSUE TITLE
Error compilar

### ISSUE THREAD

**Issue by fcbahamondes** [IIC2133-PUC/2023-1#86]
Hola, estoy intentado compilar el código sin ningún cambio, pero tengo un error el que puede ser producto de que mi computador tiene chip m2. El ayudante me dijo que para ahorrarme el problema usara docker para compilar.

Descargue docker pero de igual manera tengo un error que no he podido solucionar y me esta impidiendo avanzar con la tarea. Adjunto imagen del error.

<img width="907" alt="Captura de pantalla 2023-04-24 a las 18 51 08" src="https://user-images.githubusercontent.com/80771151/234132969-eb434130-7673-41e2-a9d5-d74c60b14050.png">

**Comment by CarloGauss33** [comment]
Solucionado por telegram
