### ISSUE TITLE
WRONG OUTPUT servidor

### ISSUE THREAD

**Issue by AngelBachler** [IIC2133-PUC/2023-1#90]
Holaa, en la parte de bst he comparado las soluciones del drive (con diff) y me salen correctas, pero en el servidor me tira WRONG OUTPUT y no sé por qué.

**Comment by sebamoreno2811** [comment]
me pasa lo mismo en la parte 3

**Comment by alexandra-maker** [comment]
Holaa, me pasa lo mismo con bst :( no logro identificar el problema

**Comment by CataAlamos** [comment]
Hola! Lo mas probable es que se este subiendo mal a github, tambien revisa bien tu archivo por si tienes algun printf que te puede dar error.

**Comment by alexandra-maker** [comment]
Lo he revisado y todo, y sigue sin funcionar :( no sé si pueden revisar quizá porque solo son 4 los que me tiran wrong output y los comparo con diff y no hay diferencia

**Comment by AngelBachler** [comment]
También lo revisé y está todo bien, cree hasta un run_tests para bst y qsort, y me tira todos buenos ;( No sé que será lo que falla

**Comment by CarloGauss33** [comment]
Hola @alexandra-maker @AngelBachler . Si funciona bien local quedense con eso. Revisare cual es el problema, probablemente sea algo de la herramienta que usamos para comparar archivos

**Comment by CataAlamos** [comment]
Hola! Revisa bien tu gitignore que estas ignorando obj/ lo que puede estar causando tu error

**Comment by AngelBachler** [comment]
Gracias! lo voy a cambiar para ver si funciona
